# Generated by Django 3.0.5 on 2020-04-19 00:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_State', models.CharField(max_length=100)),
                ('Country_Region', models.CharField(max_length=100)),
                ('Long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Lat', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('confirmedApril17', models.CharField(max_length=100)),
                ('deathsApril17', models.CharField(max_length=100)),
                ('recoveredApril17', models.CharField(max_length=100)),
            ],
        ),
    ]
