# Generated by Django 3.0.5 on 2020-04-19 00:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_State', models.CharField(max_length=100)),
                ('Country_Region', models.CharField(max_length=100)),
                ('confirmedApril17', models.CharField(max_length=100)),
                ('deathsApril17', models.CharField(max_length=100)),
                ('recoveredApril17', models.CharField(max_length=100)),
                ('Loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
