# Generated by Django 3.0.5 on 2020-04-25 17:55

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path 




DATA_FILENAME = 'april24.json'


def load_data(apps, schema_editor):
	Covid = apps.get_model('april24','april24')
	jsonfile = DATA_FILENAME

	with open(str(jsonfile), encoding = 'utf8') as datafile:
		objects = json.load(datafile)
		for obj in objects:
			Country_Region = obj['field_1']
			confirmedApril24 = obj['field_4']
			longitude = obj.get('field_3', 0)
			latitude = obj.get('field_2',0)
			location = fromstr(f'POINT({float(longitude)} {float(latitude)})', srid=4326)
			Covid(Country_Region=Country_Region,confirmedApril24=confirmedApril24, location=location).save()
				
		

class Migration(migrations.Migration):

    dependencies = [
        ('april24', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_data)
    ]



